# This is a basic workflow to help you get started with Actions

name: Full-Site-Build

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Build-Main:
    if: ${{ github.ref == 'refs/heads/main' }}
    uses: dynamsoft-docs/Docs-Template-Repo/.github/workflows/called-workflow-build-sync-production.yml@main
    with:
      doc-repo: barcode-reader-docs-server
      doc-url: barcode-reader/docs/server
    secrets: inherit

    
  Build-Preview:
    if: ${{ github.ref == 'refs/heads/preview' }}
    # The type of runner that the job will run on
    runs-on: [self-hosted, r3]

    steps:
      - name: clear space
        run: |
          cd /home/ubuntu 
          [ -d DBRDocServer-preview ] && rm -rf DBRDocServer-preview 
          [ -d barcode-reader-docs-server-preview ] && rm -rf barcode-reader-docs-server-preview
          [ -d Docs-Template-Repo-Preview-R3 ] && rm -rf Docs-Template-Repo-Preview-R3

      # Runs a set of commands using the runners shell
      - name: Build the Full site (not incremental)
        run: |
          cd /home/ubuntu
          mkdir -p DBRDocServer-preview
          git clone --depth 1 --branch preview https://github.com/dynamsoft-docs/barcode-reader-docs-server.git barcode-reader-docs-server-preview
          git clone --depth 1 --branch preview https://github.com/dynamsoft-docs/Docs-Template-Repo.git Docs-Template-Repo-Preview-R3
          cp -rfp ./barcode-reader-docs-server-preview/* ./DBRDocServer-preview/
          cp -rfp ./Docs-Template-Repo-Preview-R3/* ./DBRDocServer-preview/
          sed -i -e "1,3s/blob\/master$/blob\/preview/" \
          -e "1,3s/blob\/main$/blob\/preview/" /home/ubuntu/DBRDocServer-preview/_config.yml
          cd DBRDocServer-preview  && bundle install && bundle exec jekyll build

  Upload-Preview:
    if: ${{ github.ref == 'refs/heads/preview' }}
    # The type of runner that the job will run on
    runs-on: [self-hosted, r3]
    needs: Build-Preview

    steps:
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_TEST_SITE_SERVER }}
          username: ${{ secrets.FTP_TEST_SITE_USER }}
          password: ${{ secrets.FTP_TEST_SITE_PASSWORD }}
          port: 7500 
          local-dir: /home/ubuntu/DBRDocServer-preview/_site/
          server-dir: /www.dynamsoft.com/barcode-reader/docs/server/       
